### ISSUE TITLE
test_path folder structure

### ISSUE THREAD

**Issue by appricot-project** [nie-lang/UDIS2#5]
Hi there! Thanks for great research work!
According to readme files there is test_path folder expecting to have input1 and input2 folders with JPG files inside. I've created testing folder right this:
./testing
-- input1
---- test1.jpg
-- input2
---- test2.jpg

with files from Carpark-DHW folder.
Trying to run warp with modified testing folder path. Script is fetching images but failing with following error:

```
##################start testing#######################
Traceback (most recent call last):
  File "C:\Sources\UDIS2\Warp\Codes\test.py", line 123, in <module>
    test(args)
  File "C:\Sources\UDIS2\Warp\Codes\test.py", line 67, in test
    batch_out = build_model(net, inpu1_tesnor, inpu2_tesnor, is_training=False)
  File "C:\Sources\UDIS2\Warp\Codes\network.py", line 128, in build_model
    H_motion, mesh_motion = net(input1_tensor, input2_tensor)
  File "C:\Users\assol\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Sources\UDIS2\Warp\Codes\network.py", line 487, in forward
    offset_1 = self.regressNet1_part2(temp_1)
  File "C:\Users\assol\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\assol\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "C:\Users\assol\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\assol\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x3840 and 4096x4096)
```

What I'm doing wrong?

**Comment by nie-lang** [comment]
The test.py is used for evaluating the UDIS-D dataset. It's unsuitable for other images with other resolutions (not 512*512).

Please try test_output.py or test_other.py following the readme.md instead.
